client_config_backend: file
client_config:
    client_id: 43732180829-uk72kvvdpm7l6shr3dqb1b48a1i3ds2u.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive