# Generated by Django 4.1.3 on 2023-02-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignIntroduceDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("introduce_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "introduce_detail_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("step", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "assign_introduce_details",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AssignMaterialOutsoucing",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "outsourcing_product_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "outsourcing_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "outsourcing_percent",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "product_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_calculated", models.IntegerField()),
                (
                    "outsourcing_stock_out",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
            ],
            options={
                "db_table": "assign_material_outsoucing",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CheckMaterialReport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("unique_id", models.CharField(blank=True, max_length=254, null=True)),
                ("code", models.CharField(blank=True, max_length=250, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=255, null=True)),
                ("total_record", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "check_material_report",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CheckMaterialReportDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("req_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("material", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "db_in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "db_temporary_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "db_imported",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "db_exported",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "db_begin_quan_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "db_final_quan_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "file_in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "file_temporary_deduction",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "file_imported",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "flie_exported",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "file_begin_quan_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "file_final_quan_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "check_material_report_detail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IntroduceDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "introduce_details",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Introduces",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "introduces",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IntroUserTrackings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("introduce_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "assign_introduce_detail_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("is_skip", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "intro_user_trackings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MarkedReportHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "begin_need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "begin_need_for_outsourcing",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "begin_ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "begin_in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "begin_outsourcing_stock_out",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "begin_temporary_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "begin_need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_for_outsourcing",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "outsourcing_stock_out",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "temporary_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "marked_report_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialReportHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "product_unit_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_for_outsourcing",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_need_for_outsourcing",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outsourcing_stock_out",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_outsourcing_stock_out",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "temporary_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_temporary_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
            ],
            options={
                "db_table": "material_report_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialReports",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "product_unit_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_for_outsourcing",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("is_calculated", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outsourcing_stock_out",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "temporary_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
            ],
            options={
                "db_table": "material_reports",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderTracking",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("old_data", models.TextField(blank=True, null=True)),
                ("new_data", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "order_tracking",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReportPrimaryProductNeeds",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "product_unit_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quantity_for_secondary",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
            ],
            options={
                "db_table": "report_primary_product_needs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReportProductNeedHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "report_product_need_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "old_need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
            ],
            options={
                "db_table": "report_product_need_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReportProductNeedPrimaryHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "report_primary_product_need_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "quantity_for_secondary",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                (
                    "old_quantity_for_secondary",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "report_product_need_primary_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReportProductNeeds",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "product_unit_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "need_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "need_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "in_stock",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "report_product_needs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReqChangeProductHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "req_change_product_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("table_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "column_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_new",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_old",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "row_change_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "req_change_product_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReqMergeProductHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "req_merge_product_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("table_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "column_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_new",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "content_old",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "row_change_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "req_merge_product_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RequestAdjustImportOrderHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "request_adjust_import_order_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("table_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "record_id_change",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "record_column_change",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "old_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "new_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "request_adjust_import_order_history",
                "managed": False,
            },
        ),
    ]
