# Generated by Django 4.1.3 on 2023-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_assignintroducedetails_assignmaterialoutsoucing_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Companies",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "companies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyBranchs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("company_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("media_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "company_branchs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DepartmentBranchs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "department_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("branch_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "department_branchs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DepartmentPositions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "department_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("position_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("function_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("type_name", models.CharField(blank=True, max_length=255, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "department_positions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DepartmentRelated",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "department_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "related_department_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "department_related",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("code", models.CharField(blank=True, max_length=250, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("parent_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "departments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DepartmentUrl",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "department_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("local_url", models.CharField(blank=True, max_length=255, null=True)),
                ("dev_url", models.CharField(blank=True, max_length=255, null=True)),
                ("test_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "department_url",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FailedJobs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("connection", models.TextField()),
                ("queue", models.TextField()),
                ("payload", models.TextField()),
                ("exception", models.TextField()),
                ("failed_at", models.DateTimeField()),
            ],
            options={
                "db_table": "failed_jobs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Functions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("code", models.CharField(blank=True, max_length=250, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("url", models.TextField(blank=True, null=True)),
                ("parent_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("branch_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("company_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
                ("is_show", models.BigIntegerField()),
            ],
            options={
                "db_table": "functions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("queue", models.CharField(max_length=255)),
                ("payload", models.TextField()),
                ("attempts", models.PositiveIntegerField()),
                ("reserved_at", models.PositiveIntegerField(blank=True, null=True)),
                ("available_at", models.PositiveIntegerField()),
                ("created_at", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "jobs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JobStatuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(max_length=255)),
                ("queue", models.CharField(blank=True, max_length=255, null=True)),
                ("attempts", models.IntegerField()),
                ("progress_now", models.IntegerField()),
                ("progress_max", models.IntegerField()),
                ("status", models.CharField(max_length=16)),
                ("input", models.TextField(blank=True, null=True)),
                ("output", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_statuses",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Medias",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("source", models.CharField(blank=True, max_length=500, null=True)),
                ("domain", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "medias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Migrations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("migration", models.CharField(max_length=255)),
                ("batch", models.IntegerField()),
            ],
            options={
                "db_table": "migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OauthAccessTokens",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("client_id", models.PositiveBigIntegerField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("scopes", models.TextField(blank=True, null=True)),
                ("revoked", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_access_tokens",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OauthAuthCodes",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("user_id", models.PositiveBigIntegerField()),
                ("client_id", models.PositiveBigIntegerField()),
                ("scopes", models.TextField(blank=True, null=True)),
                ("revoked", models.IntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_auth_codes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OauthClients",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("secret", models.CharField(blank=True, max_length=100, null=True)),
                ("provider", models.CharField(blank=True, max_length=255, null=True)),
                ("redirect", models.TextField()),
                ("personal_access_client", models.IntegerField()),
                ("password_client", models.IntegerField()),
                ("revoked", models.IntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_clients",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OauthPersonalAccessClients",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("client_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_personal_access_clients",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OauthRefreshTokens",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("access_token_id", models.CharField(max_length=100)),
                ("revoked", models.IntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_refresh_tokens",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PasswordResets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "password_resets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PositionFunctions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("position_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("function_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("type_name", models.CharField(blank=True, max_length=255, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "position_functions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Positions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("code", models.CharField(blank=True, max_length=250, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("duty", models.TextField(blank=True, null=True)),
                ("responsibility", models.TextField(blank=True, null=True)),
                ("branch_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("company_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("parent_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "positions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PositionSalary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("position_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "position_salary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserCompany",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("company_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("branch_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_company",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserDepartments",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "department_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_departments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserDeptPositions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("position_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_dept_positions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserFunctions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("function_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_dept_pos_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "user_functions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "user_function_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("permission", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserPosSalary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "user_salary_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "user_pos_salary_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_pos_salary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("fullname", models.CharField(blank=True, max_length=500, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=250, null=True)),
                ("sex", models.SmallIntegerField(blank=True, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("temporary_address", models.TextField(blank=True, null=True)),
                (
                    "remember_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "identity_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("tms_token", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "avatar_media_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("customer_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserSalary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=24, null=True
                    ),
                ),
                ("creator_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_salary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ZaloUsers",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("code", models.TextField(blank=True, null=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("expires_in", models.CharField(blank=True, max_length=255, null=True)),
                ("scope", models.TextField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("uid", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "zalo_users",
                "managed": False,
            },
        ),
    ]
